load:
    login_code_description: "<h3>1. ğŸ”‘ Login code: Insert the login code you received:</h3>"
    login_code_label: "Login code"
    login_code_placeholder: "Insert login code..."
    login_code_info: "If you didn't receive a login code, please contact us."
    source_input_description: "<h3>2. ğŸ“ Source sentences: Upload a file containing source sentences to be translated OR insert source sentences manually:</h3>"
    source_file_label: "Source file"
    source_sentences_label: "Source sentences"
    source_sentences_placeholder: "Insert one source sentence per line..."
    target_input_description: "<h3>3. ğŸ“ Translated sentences: Upload a file containing pretranslated sentences OR insert translated sentences manually:</h3>"
    target_file_label: "Translated file"
    target_sentences_label: "Translated sentences"
    target_sentences_placeholder: "Insert one translated sentence per line..."
    start_button_label: "ğŸ“ Start"
translate:
    reload_button_label: "â¬…ï¸ Back to data loading"
    clear_button_label: "ğŸ—‘ï¸ Clear current changes"
    done_button_label: "âœ… Done"
    source_textbox_label: "Source text"
    target_textbox_label: "Translation"
    highlight_label: "Potential issue"