[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "geometry-py-packaging"
version = "3.0.0"
authors = [
  { name="TomGe", email="tom.gt@foxmail.com" },
]
description = "Python Packaging Tutorial by Tom Ge"
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
  'numpy; python_version>="3.9"',
  'matplotlib; python_version>="3.9"',
]