[tool.poetry]
name = "albatros-uav"
version = "0.7.1"
description = "The tool for managing unmanned aerial vehicles missions."
authors = ["JÄ™drzej Stasik <jedrzej.stasik@gmail.com>"]
license = "LGPL-3.0-only"
readme = "README.md"
packages = [{include = "albatros"}]
repository = "https://gitlab.com/albatros-uav/albatros"
documentation = "https://albatros-uav.gitlab.io/albatros/"

[tool.poetry.dependencies]
python = "^3.9"
pymavlink = "^2.4.41"
pydantic = "^1.10.9"
redis = "^5.0.0"
pyserial = "^3.5"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"
pylint = "^2.17.4"
flake8 = "^6.0.0"
taskipy = "^1.11.0"
pytest = "^7.4.2"
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.14"
mkdocstrings-python = "^1.7.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
formatting = "python -m black . && python -m isort ."
pylint = "pylint tests albatros examples"
mypy = "python -m mypy --namespace-packages albatros examples tests"
flake8 = "poetry run python -m flake8 albatros examples tests && echo All is ok"
test = "poetry run python -m pytest"

[tool.isort]
profile = "black"
