[tool.poetry]
name = "patent-chart"
version = "0.1.25"
description = "Automated invalidity contention charts"
authors = ["Josh Hedtke"]
license = "Proprietary"
readme = "README.md"

exclude = ["experiments.ipynb"]

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
tiktoken = "^0.5.1"
pdfminer-six = "^20221105"
pydantic = "^2.4.2"
numpy = "1.25.2"
beautifulsoup4 = "^4.12.2"
sentence-transformers = "^2.3.0"
openai = "^1.10.0"


[tool.poetry.group.dev.dependencies]
pdfplumber = "^0.10.2"
jupyter = "^1.0.0"
tiktoken = "^0.5.1"
python-dotenv = "^1.0.0"
pymupdf = "^1.23.4"
pypdf2 = "^3.0.1"
pdfminer-six = "^20221105"
pypdf = "^3.16.4"
matplotlib = "^3.8.0"
tabula-py = "^2.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
