[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nwisepy"
version = "1.0.0"
authors = [
  { name="Oliver Cai", email="cjz210oliver@gmail.com" },
]
description = "A simple tool to generate pairwise testing set"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Oliver-242/ipo"

[tool.hatch.build.targets.wheel]
packages = ["src/nwisepy"]