[build-system]
requires = [
    "setuptools>=61.0", "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "iot-protocols"
version = "0.0.1-a9"
authors = [
  { name="Adrien Delhaye", email="adrien.delhaye@memoco.eu" },
]
description = "Generic IIoT protocols package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.7",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]
keywords=['python', 'iiot', 'protocols']
dependencies = [ # Optional
  "py-iec62056>=1.0.0a1",
  "paho-mqtt>=1.6.1",
  "pyserial>=3.5",
  "pymodbus==2.5.3",
  "python-snap7==1.3",
]
[project.urls]
Homepage = "https://pypi.org/manage/project/iot-protocols"