[tool.poetry]
name = "yasfpy"
version = "0.0.2"
description = "Light scattering code using T-Matrix"
authors = ["Mirza Arnaut <mirza.arnaut@tu-dortmund.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.3"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocs-autorefs = "^0.5.0"
mkdocs-coverage = "^1.0.0"
mkdocs-material = "^9.5.6"
mkdocstrings = "^0.24.0"
mkdocstrings-python = "^1.8.0"
pymdown-extensions = "^10.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
