[tool.poetry]
name = "bypasssafe"
version = "0.6"
description = "Valt de senhas e gerador"
authors = ["MarcosDalessandro <marcosdalessandroclima@ufpi.edu.br>" , "MayraCaetano <mayracaetano096@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2 = "^2.9.9"
bcrypt = "^3.2.0"
python-decouple = "^3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
