[tool.poetry]
name = "lineage-aq"
version = "1.4.0"
description = "Interactive command line interface to create and edit lineage of families."
authors = ["Aqdas Ahmad Khan <aqdasak@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/aqdasak/Lineage/"
repository = "https://github.com/aqdasak/Lineage/"
license = "MIT"
keywords = ['python', 'lineage', 'genealogy']


[tool.poetry.scripts]
lineage = "lineage_aq.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
networkx = "^2.8.5"
colorama = "^0.4.5"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
