[project]
name = "sarapy"

version = "0.3.6"
authors = [
  {name = "Lucas Baldezzari", email = "lmbaldezzari@gmail.com"},]
maintainers = [
  {name = "Lucas Baldezzari", email = "lmbaldezzari@gmail.com"}
]

dependencies = [
  "numpy",
  "matplotlib",
  "pandas",
  "scipy",
  "scikit-learn",
  "geopy",
]

readme = "README.md"