[tool.poetry]
name = "sym-sdk"
version = "v0.61.0"
description = "Sym's Python SDK"
authors = ["Sym Engineering <pypi@symops.io>"]
license = "Proprietary"
readme = "DESCRIPTION.rst"
homepage = "https://sdk.docs.symops.com/"
repository = "https://github.com/symopsio/sym-sdk"
classifiers=[
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
packages = [
  { include = "sym" },
]


[tool.poetry.dependencies]
python = "^3.8.6"
pydantic = "^1.7.3"


[tool.poetry.group.dev.dependencies]
bpython = "^0.20.1"

pre-commit = "^2.2.0"
ipython = "^8.10"

pytest = "^6.1"
pytest-mock = "^3.3.1"
pytest-cov = "^2.10"
pytest-randomly = "^3.4"
pytest-testmon = "^1.0"

autoflake = "^1.4"
autopep8 = "^1.5.4"
black = "^22.1.0"
flake8 = "^3.8.4"
flake8-pytest-style = "^1.3"
flake8-logging-format = "^0.6"
isort = "^5.7.0"
mypy = "^0.941"
safety = "^2.3.1"
Sphinx = "^4.4.0"
astor = "^0.8.1"
pylint = "^2.13.0"
dunamai = "^1.5.4"
furo = "^2021.2.28-beta.28"
sphinx-sitemap = "^2.2.0"
autodoc-pydantic = "^1.8.0"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "100"

[tool.black]
line-length = 100
target-version = ['py37', 'py38']
include = '(src\/scripts\/.*$|\.pyi?$)'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
