[tool.poetry]
name = "superscraper"
version = "0.3.8"
description = "the friendliest scraper around"
authors = ["Mbeebe <pyn-sol@beebe.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.11.1"
selenium = "^4.2.0"
webdriver-manager = "^3.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
