[project]
name = "pybpf"
version = "1.0.1"
authors = [
  { name="El Mehdi SLAOUI", email="mehdislaoui14@gmail.com" },
]
description = "A python library to read bpf files"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'numpy >= 1.25.2',
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tools.setuptools]
packages = ["src"]
